server:
  port: 8888

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.0.60.147:3306/data_model?serverTimezone=Asia/Shanghai&useSSL=false&autoCommit=true&useUnicode=true&amp;characterEncoding=utf8&amp;autoReconnect=true
    username: root
    password: Bizseer@2020
  